version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - API_KEY=${API_KEY}
      - MONGODB_URI=mongodb://mongodb:27017/shadowrun
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - shadowrun_network

  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - shadowrun_network

networks:
  shadowrun_network:
    driver: bridge

volumes:
  mongodb_data: